defaults:
    - _self_
    - override hydra/hydra_logging: disabled  
    - override hydra/job_logging: disabled 
    

seed: ${seed}
exp_name: cfg_a
env_name: ${env_name}
agent_name: ${agent_name}
run_id: ??? # decided during execution

train_episodes: ${train_episodes}
gamma: 0.99
lr: 2e-3

random_episodes: 10

testing: ${testing}
model_path: default

save_video: false
save_logging: false
save_model: true
use_wandb: true
silent: false
glie_b: 200
run_suffix: 0
# ref: https://stackoverflow.com/questions/65104134/disable-file-output-of-hydra
hydra:  
    output_subdir: null  
    run:  
        dir: .
